
set -g prefix C-a
unbind C-a
bin C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1

set -g mouse on

bind '|' split-window -h
bind '\\' split-window -v
bind 'c' new-window

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5

bind r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

set -g window-status-format ""
set -g window-status-current-format ""
set -g status-left-length 100
set -g status-right-length 100
set -g status-interval 1


# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'

# continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# resurrect
set -g @resurrect-strategy-nvim 'session'

# navigation
set -g @vim_navigator_mapping_left 'M-Left'
set -g @vim_navigator_mapping_right 'M-Right'
set -g @vim_navigator_mapping_up 'M-Up'
set -g @vim_navigator_mapping_down 'M-Down'

# stats
set -g status-left 'time: %H:%M:%S'
set -g status-right 'cpu: #{cpu_percentage} | ram: #{ram_percentage} | session: #{session_name} | host: #{host}'


run '~/.config/tmux/plugins/tpm/tpm'
